name: nordic_lbs_client_demo
description: A client application for nRF Connect SDK peripheral_lbs sample

version: 0.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
#  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true